README.rst
mpisppy/__init__.py
mpisppy/tests/test_ef_ph.py
mpisppy/utils/sputils.py

I added a function to disable tictoc output, but it won't yet disable the output created by __init__; I could live with that for
now, but maybe someone has a good idea for how to disable that as well (and still get a really good tictoc starting point, which
is also important)

[WIP] Add some ability to disable tictoc output

---

.github/workflows/pyotracker.yml
.github/workflows/twiceweekly.yml
.github/workflows/weekly.yml
README.rst
docker-actions/weekly/Dockerfile

Add an action to test against Pyomo master every night. I also think I correctly added a badge for this.

Track pyomo tests

---

.github/workflows/twiceweekly.yml
examples/run_all.py

move a sizes example so that longer github tests based on xpress can run

---

doc/src/extensions.rst
examples/sizes/special_cylinders.py
examples/sizes/special_sizes.py
examples/tryone.py
mpisppy/phbase.py
mpisppy/spbase.py
mpisppy/utils/vanilla.py

This now executes and I have a sizes example that can be run
cd examples
python tryone.py <solver>
As predicted, zeroing out a variable from one scenario does not make a difference. I need to come up with an example
where the solution changes in a sensible way.

Prob coeffs

---

examples/hydro/hydro_ef.py
examples/netdes/netdes_ef.py
examples/run_all.py
examples/uc/uc_ef.py
mpisppy/opt/ef.py
mpisppy/spbase.py

Fixing issue with multistage EF

---

mpisppy/extensions/extension.py
mpisppy/spbase.py

The commit messages are a big confusing, but this is now mainly Ben's post_solve extension callback, plus an unrelated improvement to an error message.

Post solve ext

---

mpisppy/phbase.py

Being more permissive with termination conditions in PHBase.solve_one

---

doc/src/hubs.rst
doc/src/index.rst
doc/src/secretmenu.rst
mpisppy/phbase.py
mpisppy/utils/baseparsers.py
mpisppy/utils/vanilla.py

I am adding a little documentation, but it is not yet doctested. I still think we should add it.

Secretmenu

---

mpisppy/phbase.py

- adding default verbose=False to subproblem_creation
- finishing asynchronousPH clean-up

Minor cleanup in PHBase

---

doc/src/extensions.rst
examples/run_all.py
examples/tryone.py
mpisppy/extensions/diagnoser.py
mpisppy/opt/ph.py
mpisppy/utils/sputils.py

Add a little documentation and touch up an unused extension

A little new documentation and miscellaneous cleanup

---

mpisppy/opt/aph.py
mpisppy/tests/test_aph.py

aph support for with-display-convergence-detail

Aphdisplay

---

mpisppy/__init__.py
mpisppy/opt/aph.py
mpisppy/tests/test_aph.py
mpisppy/tests/test_pysp_model.py
mpisppy/utils/listener_util/demo_listener_util.py
mpisppy/utils/listener_util/listener_util.py
mpisppy/utils/pysp_model.py

Closes #19 and closes #82.
Addresses import issues around TicTocTimer and PySP.

Pyomo6 mod LShaped

---

doc/src/scenario_creator.rst

No functional change; just a tweak to the documentation

clarifying nonant_ef_supple_list

---

.github/workflows/testaph.yml
examples/farmer/farmer_cylinders.py
examples/farmer/quartz/NOTES.txt
examples/run_all.py
mpisppy/opt/aph.py
mpisppy/tests/test_aph.py
mpisppy/utils/baseparsers.py
mpisppy/utils/vanilla.py

wait for PR#94 to be merged, then delete PR#97 and merge this one

Add tests for Pr 97; this should subsume PR#97

---

mpisppy/opt/aph.py
mpisppy/phbase.py
mpisppy/spopt.py

subproblem_creation now adds bundle info to scenario data and aph uses it.
Is a replacement for #98.

bundle info on scenarios to support aph

---

mpisppy/utils/vanilla.py

scenario denouement was being dropped on the floor by many methods in the vanilla grab-bag.

Vanilla fix

---

examples/hydro/hydro_ef.py

so it will be tested by run_all

add use of report_var_values_at_rank0 to the hydro_ef example 

---

examples/farmer/farmer_cylinders.py
examples/farmer/farmer_ef.py
mpisppy/spbase.py
mpisppy/utils/sputils.py

npy writers for xhat nonants
This is "tested" in run_all. At least the ef writer will be in a unit tests for MMW very soon.

Xhatnonants

---

.github/workflows/pyotracker.yml
.github/workflows/testpysp.yml

PySP (plus drop pyutilib from pyomo tracker)

PySP interface test

---

mpisppy/cylinders/slam_heuristic.py

Fixing bug introduced by me in #122.

Adding _update_E1 to slammer

---

mpisppy/confidence_intervals/seqsampling.py
mpisppy/tests/test_conf_int.py

Changing the way to compute sample size

Minor fix in seqsampling

---

doc/src/scenario_creator.rst
examples/afew.py
mpisppy/opt/lshaped.py
mpisppy/spopt.py
mpisppy/utils/lshaped_cuts.py

adding function for set_instance retries

---

examples/aircond/aircond_cylinders.py
examples/aircond/aircond_ef.py
examples/run_all.py

adding 4-stage aircond example

---

mpisppy/confidence_intervals/ciutils.py
mpisppy/confidence_intervals/mmw_ci.py
mpisppy/confidence_intervals/seqsampling.py
mpisppy/tests/examples/aircond_submodels.py

- sequential sampling pooling
- multi-stage optimality gap (for MMWConfidenceInterval)
- xhat_generator_aircond passes start_seed
- changed a few examples to check pooling

Small fixes

---

examples/aircond/aircond_ef.py
mpisppy/confidence_intervals/mmw_ci.py
mpisppy/confidence_intervals/mmw_conf.py
mpisppy/tests/test_conf_int.py

Rationalize start scenario for MMW

Start scen

---

examples/farmer/farmer_cylinders.py
examples/hydro/hydro_cylinders.py
examples/hydro/hydro_cylinders_pysp.py
mpisppy/cylinders/__init__.py
mpisppy/cylinders/cross_scen_hub.py
mpisppy/cylinders/spcommunicator.py
mpisppy/cylinders/spoke.py
mpisppy/spbase.py
mpisppy/spin_the_wheel.py
mpisppy/utils/vanilla.py

Spoke sleep time

---

doc/src/amalgomator.rst
examples/aircond/aircond_seqsampling.py
examples/aircond/aircond_sequential.bash
examples/farmer/afarmer.py
mpisppy/confidence_intervals/ciutils.py
mpisppy/confidence_intervals/mmw_ci.py
mpisppy/confidence_intervals/mmw_conf.py
mpisppy/confidence_intervals/multi_seqsampling.py
mpisppy/confidence_intervals/sample_tree.py
mpisppy/confidence_intervals/seqsampling.py

Mainly adding docstrings and other documentation

Confoptions

---

doc/src/hubs.rst
examples/farmer/farmer_cylinders.py
examples/run_all.py
examples/sizes/sizes_demo.py
mpisppy/convergers/norm_rho_converger.py
mpisppy/extensions/norm_rho_updater.py
mpisppy/fwph/fwph.py
mpisppy/opt/aph.py
mpisppy/opt/ph.py
mpisppy/phbase.py
mpisppy/utils/vanilla.py

hub converger support, doc, and run_all "test"; rho_updater signals to norm_rho converger that it is active

Convergers (small PR)

---

examples/aircond/aircond_ef.py
examples/aircond/demo.bash
mpisppy/tests/examples/aircond.py
mpisppy/tests/test_conf_int_aircond.py

fix some bugs in aircond and add a demo.bash script to examples/aircond

Aircondbug

---

mpisppy/extensions/norm_rho_updater.py

The norm rho update would sometimes fail for multistage models. This PR fixes that issue.

Making rho updater work for multistage problems

---

mpisppy/tests/examples/aircond.py
mpisppy/tests/test_conf_int_aircond.py

Do a better job with inventory costs.

Improve aircond model

---

examples/netdes/netdes.py
mpisppy/scenario_tree.py

...with example in netdes. Maybe we have a better example?

Adding support for slices

---

.github/workflows/straight.yml
.github/workflows/testbunpick.yml
doc/src/amalgamator.rst
doc/src/index.rst
doc/src/pickledbundles.rst
examples/aircond/aircond_cylinders.py
examples/aircond/allways.bash
examples/aircond/bundle_pickler.py
examples/aircond/pickler.py
examples/aircond/proper_bundle_demo.bash
examples/aircond/try_pickles.bash
mpisppy/cylinders/xhatshufflelooper_bounder.py
mpisppy/tests/examples/aircond.py
mpisppy/tests/examples/aircondB.py
mpisppy/tests/straight_tests.py
mpisppy/tests/test_conf_int_aircond.py
mpisppy/tests/test_pickle_bundle.py
mpisppy/utils/amalgamator.py
mpisppy/utils/pickle_bundle.py
mpisppy/utils/sputils.py

Pickle bundle

---

.readthedocs.yml
requirements.txt
setup.py

update setup.py and requirements.txt

Readthedocs II

---

.readthedocs.yml
mock_mpi4py/mpi4py/__init__.py
mock_mpi4py/setup.py
requirements.txt
setup.py

Readthedocs

---

doc/src/amalgamator.rst
doc/src/drivers.rst
doc/src/pysp.rst
doc/src/quick_start.rst
doc/src/scenario_creator.rst

Doctouchups

---

examples/hydro/cfg.bash
examples/hydro/hydro_cylinders_config.py
mpisppy/utils/cfg_vanilla.py
mpisppy/utils/config.py
mpisppy/utils/vanilla.py

A non-disruptive proposal for switching to the pyomo config system.
utils.config.py has the config object
utils.cfg_vanilla.py is a version of vanilla.py that is compatible.
examples.hydro.hydro_cylinders_config.py is an example that uses them and examples.hydro.cfg.bash runs that example

Global config

---

mpisppy/spbase.py

This is harmless, but helpful to me

add an option to disable the popular-with-some toc Initializing SPBase

---

examples/netdes/netdes_cylinders.py
examples/run_all.py
mpisppy/cylinders/slam_heuristic.py
mpisppy/utils/amalgamator.py
mpisppy/utils/baseparsers.py
mpisppy/utils/cfg_vanilla.py
mpisppy/utils/config.py
mpisppy/utils/vanilla.py

@jeanpaulwatson and I agree that these names are slightly more appropriate, as we don't slam to a bound.

Rename slamup/slamdown slammax/slammin

---

.github/workflows/publish-to-test-pypi.yml
.github/workflows/schur_complement.yml
setup.py

Already an implicit requirement; this would make it explicit.

Require Python 3.8+

---

mpisppy/tests/examples/aircond.py

minor change to the aircond example

added branching factors to inparser

---

setup.py

I was typing too fast in #266.

Allow Python 3.8.0

---

examples/acopf3/rho_setter.py
examples/farmer/farmer_ef.py
mpisppy/confidence_intervals/ciutils.py
mpisppy/opt/ef.py
mpisppy/phbase.py
mpisppy/spbase.py
mpisppy/utils/amalgamator.py
mpisppy/utils/config.py
mpisppy/utils/solver_options.py
mpisppy/utils/solver_spec.py
mpisppy/utils/sputils.py

A simple proposal for consistent handling of solver names and options. See mpisppy.utils.solver_spec.py for comments; see amalgagmator and examples/sizes/sizes_ef for examples of use.
I also fixed a bug in the check for required options, which caused test failures and will probably be somewhat disruptive (although with good error messages).

[WIP] Solver hierarchy

---

examples/run_all.py
mpisppy/confidence_intervals/ciutils.py
mpisppy/confidence_intervals/mmw_ci.py
mpisppy/confidence_intervals/mmw_conf.py

remove objective_gap option from MMW

remove objective_gap option

---

mpisppy/utils/config.py
mpisppy/utils/sputils.py

minor changes to cfg setup and drop an bad, unused function from utils

preparing for cleaner, more general solver options

---

mpisppy/spbase.py

Adding a check for per-variable probabilities, ensuring (within tolerance) that they sum to unity

Adding omitted-but-critical variable probability sum check.

---

examples/farmer/farmer.py
mpisppy/confidence_intervals/ciutils.py
mpisppy/confidence_intervals/multi_seqsampling.py

minor changes to farmer plus suppressing a warning for max problems in confidence interval code

Farmer repair

---

examples/aircond/aph.slurm
examples/aircond/demo.slurm
mpisppy/confidence_intervals/ciutils.py
mpisppy/opt/aph.py
mpisppy/tests/test_conf_int_farmer.py
mpisppy/utils/sputils.py

fix a bug in display timing for aph

Aph dtiming

---

mpisppy/opt/aph.py
mpisppy/spopt.py

collecting solve times for all solves on a rank and including the objective function update for persistent solvers in the time

repairing solve timing for PH and APH

---

doc/src/extensions.rst
mpisppy/phbase.py

adding new optional callback to extensions after spcomm.sync in iter 0 and iter k

now calling extensions after sync in ph iter

---

examples/farmer/farmer_zhat.bash
mpisppy/utils/sputils.py

make it so EF formation support "uniform" probability specification (and update a sample bash script)

Uniform ef

---

examples/sizes/special_cylinders.py
examples/uc/uc_cylinders.py
mpisppy/phbase.py
mpisppy/utils/find_rho.py

clean up accesses to s._mpisppy_data.prob_coeff when probability is variable

Variable probability

---

.github/workflows/schur_complement.yml
.github/workflows/straight.yml
.github/workflows/testbunpick.yml
.github/workflows/testconfint.yml
.github/workflows/testgradient.yml
mpisppy/convergers/primal_dual_converger.py
mpisppy/extensions/phtracker.py
mpisppy/utils/cfg_vanilla.py

Remove matplotlib

---

mpisppy/extensions/phtracker.py
mpisppy/utils/cfg_vanilla.py

should take care of the little code which was specific to the hub bounds to spoke implementation

fixed phtracking reliant on hub bounds code

---

examples/farmer/farmer_cylinders.py
mpisppy/cylinders/ph_ob.py
mpisppy/utils/cfg_vanilla.py
mpisppy/utils/config.py
mpisppy/utils/wtracker.py

Outer bounder using PH with smaller rhos to compute a lower bound.
There are different ways of selecting rho values:
- by default (rescaling of hub value)
- manually
- use a json file with scaling factors
- use gradient-based rho (not tested)

ph outer bounder

---

.github/workflows/testwithcylinders.yml
doc/src/extensions.rst
mpisppy/extensions/test_extension.py
mpisppy/extensions/xhatxbar.py
mpisppy/phbase.py
mpisppy/spbase.py
mpisppy/spopt.py
mpisppy/tests/test_with_cylinders.py
mpisppy/utils/cfg_vanilla.py
mpisppy/utils/sputils.py
mpisppy/utils/xhat_eval.py

Closes #345 
Allowed for extensions in many spokes
Some standardization in cfg_vanilla
Added a little doc concerning multiple extensions

Some spoke extensions

---

mpisppy/cylinders/xhatlooper_bounder.py
mpisppy/cylinders/xhatshufflelooper_bounder.py
mpisppy/extensions/xhatlooper.py
mpisppy/tests/examples/farmer.py
mpisppy/tests/helper_extension.py
mpisppy/tests/test_with_cylinders.py

Partially fix for #357 
Xhatters that loop need to restore nonants during the loop, added a test to check this for xhatshufflelooper

Shufflefix

---

mpisppy/__init__.py

Fixes #364.
Thanks to @jsiirola for the helpful suggestions https://github.com/Pyomo/pyomo/issues/3091#issuecomment-1892906628.

Pre-register numpy types in Pyomo

---

doc/src/scenario_creator.rst
mpisppy/spbase.py

work on scenario creator docs and make unrelated changes to some error messages in spbase

Two cleanups

---

mpisppy/cylinders/lagranger_bounder.py
mpisppy/cylinders/lagrangian_bounder.py
mpisppy/cylinders/subgradient_bounder.py

add PH extensions to lagrangian bounders

---

mpisppy/generic_cylinders.py

bug fix for fixer; add reduced cost fixer

adding to generic_cylinders

---

examples/generic_cylinders.bash
mpisppy/extensions/sensi_rho.py
mpisppy/utils/nonant_sensitivities.py

move sensitivity code to utils from the extension that uses it

---

.github/workflows/test_pr_and_main.yml
mpisppy/fwph/fwph.py

Fixes #442. Adds additional runall runner for direct solvers.

Fix bug in FWPH with Pyomo 6.8

---

mpisppy/cylinders/reduced_costs_spoke.py
mpisppy/utils/nonant_sensitivities.py

...for reduced costs spoke and nonant sensitivity calculation.

Bugfixes involving modeler fixed variables

---

mpisppy/extensions/reduced_costs_rho.py

Fix bug when RCs are nan

---

mpisppy/cylinders/reduced_costs_spoke.py

1. handle nonants without bounds
2. handle improper bundles

RC spoke bugfixes

---

mpisppy/cylinders/xhatlooper_bounder.py
mpisppy/cylinders/xhatshufflelooper_bounder.py

...and a few other minor changes.

XhatShuffleInnerBound: always try at least two scenarios

---

mpisppy/cylinders/hub.py
mpisppy/opt/subgradient.py
mpisppy/utils/cfg_vanilla.py

Along the way, I made the following changes:
1. Explicit SubgradientHub
2. Hubs register if their host algorithm is providing bound

Bugfix: subgradient_main incorrectly runs PH

---

mpisppy/agnostic/agnostic_cylinders.py
mpisppy/agnostic/examples/farmer.py
mpisppy/agnostic/examples/farmer_ampl_model.py
mpisppy/agnostic/examples/farmer_gurobipy_model.py
mpisppy/agnostic/examples/steel_ampl_model.py
mpisppy/agnostic/farmer4agnostic.py
mpisppy/spopt.py
mpisppy/tests/examples/aircond.py
mpisppy/tests/examples/aircondB.py
mpisppy/tests/examples/apl1p.py
mpisppy/tests/examples/farmer.py
mpisppy/tests/examples/gbd/gbd.py
mpisppy/utils/admmWrapper.py
mpisppy/utils/callbacks/termination/tests/markshare2.py

Do things that are easy to do in response to pylint

Pylint easy stuff

---

mpisppy/utils/config.py

Should have listened to copilot

fixing bug when there is an empty line in config file
