mpisppy/spbase.py
For a 3-stage problem with 2 first-stage variables and 3 second-stage variables:
master:
```
_PySP_nlens: {'ROOT': 2, 'ROOT_2': 3}
_PySP_cistart: {'ROOT': 0, 'ROOT_2': 3}
```
PR:
```
_PySP_nlens: {'ROOT': 2, 'ROOT_2': 3}
_PySP_cistart: {'ROOT': 0, 'ROOT_2': 2}
```
=> Fixing logic for cistart

mpisppy/phbase.py
Uses a bit of extra memory to move a several operations into C. This should obviously be carefully checked and verified.
Also renames `node_concats` to `global_concats` in Compute_Xbar.
=> More numpythonic Compute_Xbar

mpisppy/phbase.py
This method only touches `scenario._Ws`, which are updated for persistent solvers in `PHBase.solve_one` by `PersistentSolver.set_objective`.
=> Remove unneeded persistent solver gymnastics in PHBase.W_from_flat_list

mpisppy/extensions/xhatbase.py, mpisppy/spbase.py
This PR is being superseded by a branch Ben started that allows for callbacks after every subproblem solve. I am going merge it with the (unrelated) improvement to an error message.
Old Text:
I happen to need to have xhatters call the post_iter0 on the extension on the opt object that they own (never mind that the
xhatter itself might be an extension). 
As luck would have it, it turns out that post_iter0 is the only callback that was easy.  I'm not quite sure how, or even whether, the other extension calls should be supported.  (Iter 0 is very special in our implementation of PH, so the post-iter0 extension
call is sometimes the only one needed).
=> NOW: minor error message improvement; WAS (but is no longer): xhatbase now calls the post_iter0 for an extension *on* *its* opt object

examples/run_all.py, mpisppy/cylinders/lagrangian_bounder.py
changes to run_all.py to try to get the bi-weekly tests to be able to complete in less than three
hours (xpress hates the sizes problem)
=> making sizes use linearize so xpress might be able to run longer tests

mpisppy/__init__.py, mpisppy/cylinders/cross_scen_spoke.py, mpisppy/cylinders/hub.py, mpisppy/extensions/cross_scen_extension.py, mpisppy/phbase.py, mpisppy/spbase.py, mpisppy/utils/sputils.py
This PR adds a wrapper around `mpisppy.tt_timer.toc` called `global_toc`. `mpisppy.global_toc` takes two arguments, a message and an optional conditional. If the conditional is `False`, nothing will be printed, otherwise `mpisppy.tt_timer.toc` is called with `delta=False`. By default the conditional is only set to `True` on global rank 0 and `False` on all other ranks.
=> Adding global_toc

mpisppy/phbase.py
Extending the check for termination condition to include not just infeasible, but infeasible, unbounded, or both.
=> Improve failed-to-solve checks

.github/workflows/publish-to-test-pypi.yml
I believe this PR will ensure the "publish-to-test-pypi" tests only get run for tagged commits. This allows GitHub Actions to be enabled on forks.
=> only run GHA to publish to pypi for tagged commits

mpisppy/opt/aph.py
Expanding the square in the APH proximal term, to (partially) mitigate cost of canonical expression computation in Pyomo.
=> Quadratic term expansion for APH

mpisppy/opt/lshaped.py
#149 points out that LShaped currently does not report a tree solution available at convergence. This PR fixes that.
=> Adding tree solution tag for lshaped

mpisppy/spbase.py, mpisppy/spopt.py
Fixes #170. Given that the solve need to touch every variable at least once when loading it into the model, this safety check on *only* the nonanticipative variables once per solve should not be onerous.
=> Add RuntimeError for stale non-anticipative variables on feasible scenarios

mpisppy/fwph/fwph.py
When thinking about #205, I found a potential performance issue in FWPH setup: the implementation of `_get_leaf_vars` had quadratic run-time in the problem size.
I also caught a place where it hadn't kept up with changes in PH.
=> FWPH patch

doc/src/ef.rst
The docs referred to `mpisppy.opt.ef.ExtensiveForm` as `mpisppy.opt.ef.EF`, which does not exist. Also, for consistency I added the full module prefix for `create_EF`.
=> Correct extensive form class and function names in docs

mpisppy/cylinders/hub.py
As-is, the message "absolute gap satisfied" will not be printed, and the "relative gap satisfied" message will be printed instead.
=> fixing copy-paste error for absolute gap

mpisppy/spopt.py
weak in the sense the scenario.name is usually unknown, on the other hand, the much more important thing is
to see the variable name.  This PR also makes a slight change in how stale is handled that might only affect gurobi solvers.
=> fix (weakly) an error message

mpisppy/cylinders/lshaped_bounder.py, mpisppy/cylinders/spoke.py
=> Storing and restoring tree solution for incumbent finders

doc/src/extensions.rst
try to warn users of variable probability that they should only use xhatxbar for upper bounds
=> A doc update for variable probability

mpisppy/spopt.py
Not sure this is a good idea -- but usually a collection of ranks fails to acquire a license all at once, and then they all wait the same amount of time before re-trying.
This attempts to put some stochasticity into the retry time. Example output:
=> random sleep with license retry

mpisppy/cylinders/xhatshufflelooper_bounder.py
Partially fixes #357.
Instead of starting a new epoch immediately at the end of the last one, start epochs when new solution sets are loaded. Scenario index is set at instantiation and does not reset with new epoch.
=> Avoid retrying the same solutions

mpisppy/cylinders/lagranger_bounder.py, mpisppy/cylinders/lagrangian_bounder.py, mpisppy/cylinders/ph_ob.py, mpisppy/extensions/cross_scen_extension.py, mpisppy/extensions/diagnoser.py, mpisppy/extensions/fixer.py, mpisppy/fwph/fwph.py, mpisppy/opt/aph.py, mpisppy/opt/ph.py, mpisppy/phbase.py, mpisppy/spopt.py, mpisppy/utils/xhat_eval.py
I want to add a new feature to `SPOpt`, but the way we create subproblems is making it awkward.
Unconditionally saves the scenario objective functions before bundle / subproblem creation.
=> Centralized subproblem creation

mpisppy/phbase.py, mpisppy/utils/prox_approx.py
- Remove "additional cuts" code
- Add first cut at `xhat` and at `2 * xbar - xhat`, which creates a vertex in the approximation at `xbar`
- In subsequent iterations, project the point `xvar, xvarsqrd` onto `xvarsqrd >= xvar * xvar` -- call the point `x_star` -- and add a cut at `x_star` and `2 * xbar - x_star`, creating a vertex in the approximation at `xbar`.
Simple demonstration: `min (x - (-73.2))**2`
`main`, `tolerance = 1e-06`:
```
x: -5.00e+01, obj: -1.96e+03
x: -5.14e+01, obj: -1.88e+03
x: -5.85e+01, obj: -1.51e+03
x: -7.06e+01, obj: -8.58e+02
x: -8.21e+01, obj: -2.42e+02
x: -7.21e+01, obj: -6.24e+01
x: -7.59e+01, obj: -1.03e+01
x: -7.37e+01, obj: -3.88e+00
x: -7.27e+01, obj: -7.77e-01
x: -7.32e+01, obj: -2.57e-01
x: -7.30e+01, obj: -4.87e-03
x: -7.31e+01, obj: -2.39e-03
x: …
```
=> Prox approx xbar

mpisppy/cylinders/lagrangian_bounder.py, mpisppy/tests/test_with_cylinders.py
This can take a significant amount of time, such that finalization is waiting on the Lagrangian bounder.
The benefit seems marginal at best -- if we've already decided to stop, let's just wrap it up.
=> Remove final Lagrangian solve

doc/src/secretmenu.rst, mpisppy/cylinders/lagrangian_bounder.py
Not sure this is a good idea -- you may miss incoming weights. Opening this draft PR for discussion.
=> add subgradient option to lagrangian

mpisppy/cylinders/lagranger_bounder.py
If Lagranger is faster than the hub to iteration 1, the nonants from the hub will be `nan`, which can cause the `W`'s to be `nan`, and then the user gets an error from the solver interface.
The PR would fix this bug.
=> Lagranger: Be sure we don't set nonants to `nan`

mpisppy/opt/ef.py
This pull request improves the documentation for the `ExtensiveForm` class by:
1. Correcting the order of arguments in the docstring to match the `__init__` method signature.
2. Adding the missing `all_nodenames` argument to the docstring.
- Updated the `ExtensiveForm` class docstring for consistency and completeness.
The previous docstring was misleading due to:
- A mismatch in the order of arguments.
- The omission of the `all_nodenames` argument.
These changes enhance the clarity and usability of the documentation, making it easier for developers to understand and use the class.
=> Correct `ExtensiveForm` docstring arg order and add missing parameter

mpisppy/phbase.py, mpisppy/utils/prox_approx.py, mpisppy/utils/sputils.py
- Re-implement cut manager based on tolerance
- Add cuts based on W
- Add safety cuts if W == 0 and xbar == xhat
- Don't bother if the variable is fixed
- Skip cut if it is outside the variable bounds
=> Prox approx part 3

doc/src/extensions.rst, examples/run_all.py, examples/sslp/sslp_cylinders.py, mpisppy/cylinders/xhatlooper_bounder.py, mpisppy/cylinders/xhatshufflelooper_bounder.py, mpisppy/cylinders/xhatspecific_bounder.py, mpisppy/cylinders/xhatxbar_bounder.py, mpisppy/extensions/integer_relax_then_enforce.py, mpisppy/extensions/xhatbase.py, mpisppy/extensions/xhatxbar.py, mpisppy/generic_cylinders.py, mpisppy/spopt.py, mpisppy/utils/cfg_vanilla.py, mpisppy/utils/config.py
=> Initial implementation of IntegerRelaxThenEnforce

.github/workflows/test_pr_and_main.yml
`ubuntu-latest` became Ubuntu 24.04, which broke our Pynumero builds. This PR fixes that.
=> Fix GHA failures

mpisppy/cylinders/spoke.py, mpisppy/cylinders/xhatlooper_bounder.py, mpisppy/cylinders/xhatshufflelooper_bounder.py, mpisppy/extensions/xhatbase.py, mpisppy/spbase.py
Follow up from #461.
The changes in #461 were needed to ensure the solution written was nonanticipative. However, as a side effect, it made the xhatters less effective. Because `XhatBase._try_one` did not restore the nonants, when the "next" scenario was called it would have the previous solution loaded, and not the PH iteration loaded. Therefore the incumbent finders were only producing at most one solution per PH iteration.
This PR fixes the same bug as #461, but does so my moving the best solution found tracking code into `SPBase`. Then the Xhatters can update and cache the solution immediately after it is found, and then finally restoring the nonants for the next try. This also makes it much less likely that solutions found will be accidentally dropped because of a user configuration …
=> fixing xhatters

.github/workflows/test_pr_and_main.yml, setup.py
#476 wants to use features in Python 3.9+. Though these features are available in Python 3.8 from `__future__`, Python 3.8 reach EOL 2024-10-07.
This PR would require at least Python 3.9 for `mpi-sppy`.
=> require Python >=3.9

.github/workflows/test_pr_and_main.yml, examples/farmer/farmer_cylinders.py, mpisppy/generic_cylinders.py, mpisppy/phbase.py, mpisppy/tests/test_gradient_rho.py, mpisppy/tests/test_w_writer.py, mpisppy/tests/test_xbar_w_reader_writer.py, mpisppy/utils/config.py, mpisppy/utils/gradient.py, mpisppy/utils/wxbarreader.py, mpisppy/utils/wxbarwriter.py
Intended as an exemplar for improving options processing and reading in mpisppy. 
Objective is to move options definition and processing into "leaf" classes, to improve encapsulation. 
This PR only does this for XBar-W reader/writer extensions, as a concise place to start.
Also actually makes use of these extensions in generic_cylinders.py - previously the options were specified, but never used.
=> Xbar-W reader writer options processing re-work

mpisppy/cylinders/spcommunicator.py
=> Comment out debug statements

doc/src/properbundles.rst, examples/sslp/sslp.py, mpisppy/utils/proper_bundler.py, mpisppy/utils/sputils.py
- Support non-uniform probabilities in proper bundles
- Support surrogate non-anticipative variables in proper bundles
- Proper bundles now doesn't build the first scenario twice
- Add `surrogate_nonant` option for SSLP when using generic_cylinders.py
- Correctly compute nonant cost coefficients when proper bundles are used
=> Enhancements for proper bundles

.github/workflows/test_pr_and_main.yml, examples/farmer/agnostic/farmer_ampl_agnostic.py, examples/farmer/agnostic/farmer_gurobipy_agnostic.py, examples/farmer/agnostic/farmer_pyomo_agnostic.py, mpisppy/agnostic/ampl_guest.py, mpisppy/agnostic/examples/farmer_gurobipy_model.py, mpisppy/agnostic/gams_guest.py, mpisppy/agnostic/pyomo_guest.py, mpisppy/cylinders/spcommunicator.py, mpisppy/cylinders/spoke.py, mpisppy/cylinders/spwindow.py, mpisppy/extensions/xhatbase.py, mpisppy/spbase.py, mpisppy/spopt.py, mpisppy/tests/test_component_map_usage.py
=> adding fields for best xhat and recent xhats

mpisppy/phbase.py
No point in continuing `iterk_loop` in this case.
=> Add return if we have cylinder convergence after iteration 0

mpisppy/utils/sputils.py
When using GAMS' solvers, there are certain infeasible solves with an `unknown` solution status return which is not flagged in the current implementation of the solution check used in xhatbase. This PR addresses that issue to avoid infeasible xhat solutions from certain ranks being considered valid by checking for the `unknown` solution status returned by GAMS.
=> Add solution status check to flag GAMS infeasible solves

mpisppy/extensions/grad_rho.py, mpisppy/utils/config.py
This PR changes the way scenario dependent denominator in GradRho is bounded:
- Earlier it was bounded using `opt.E1_tolerance`, which does not take into account magnitude scale of the non-anticipative variable.
- We now change it to bound with a relative bounding factor using the already existing `grad_rho_relative_bound` and bound it in the form `denom_bound*v.value_`  , where `denom_bound = 1/grad_rho_relative_bound` and `v.value_` is the value of the non-anticipative variable.
- This approach allows to capture the scale of magnitude with a relative bounding value with respect to each non-anticipative variable.
=> Bounding the scenario dependent denominator in GradRho with a relative bounding factor

mpisppy/opt/subgradient.py
#556 broke Subgradient bound reporting because Subgradient inherits from PH. Subgradient does not need to check if `prox_on` or not, because the prox is disabled.
The real fix would be to make PH inherit from Subgradient, which would be a cleaner algorithmic and class hierarchy. However, this would be a significant re-factor of the code.
=> Fix Subgradient lower bound reporting

examples/run_all.py, mpisppy/extensions/grad_rho.py, mpisppy/utils/config.py
=> apply denom max to independent denom
